### ISSUE TITLE
Time display and adjustement

### ISSUE THREAD

**Issue by zagi-tng** [openwisp/openwrt-openwisp-monitoring#110]
Seems that when checking local time of AP the clock displayed is 1hour off:

![Screenshot_2022-11-21_14-07-30](https://user-images.githubusercontent.com/84370013/203770238-a548c952-02e0-4506-9438-b19d7703f266.png)
![Screenshot_2022-11-21_14-11-17](https://user-images.githubusercontent.com/84370013/203770245-6df75f8e-bc80-4843-aadf-5e3a569a75c5.png)
![Screenshot_2022-11-21_14-12-06](https://user-images.githubusercontent.com/84370013/203770249-bba15a3c-1118-48b9-baa0-4903cd40211f.png)

AP is synced to ntp server and uci  settings are:

option timezone 'CET-1CEST,M3.5.0,M10.5.0/3'
option zonename 'Europe/Vienna'

openwisp server also ntp synced:

 LANG="en_US.UTF-8"
 LANGUAGE="en_US:en"
#> cat /etc/timezone 
Europe/Vienna

What also bothers me is that graphs show 24h time (which i would like), but the device and such display am/pm time.

If i disable  L10N (USE_L10N = True) then all clocks are 1h off

DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i:s'
TIME_FORMAT = 'H:i:s'

**Comment by nemesisdesign** [comment]
@zagi-tng please can you reformulate this bug report by stating clear steps to reproduce this issue, eg:

1. perform the development install in the README / install via ansible-openwisp2
2. set setting A to X, setting B to Y, etc.
3. do Z

Expected result: XX
Actual result: YY

**Comment by nemesisdesign** [comment]
I am closing for now, feel free to reopen if you can provide more information.
