### ISSUE TITLE
[feature] Add more wifi station information

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwrt-openwisp-monitoring#124]
We shall add the station to which the device is connected, plus other information taken from iwinfo like `bitrate` and `quality` and `quality_max`, if availabile.

If this is also available in adhoc and mesh mode, we should add it too.

**Comment by pandafy** [comment]
The associated clients are already added for ad-hoc and mesh mode. 

https://github.com/openwisp/openwrt-openwisp-monitoring/blob/0f829f80fcd751b005b5ff8c0923ef0ca8fef081/openwisp-monitoring/files/sbin/netjson-monitoring.lua#L95-L101
