### ISSUE TITLE
[bug] get_cpus may fail sometimes

### ISSUE THREAD

**Issue by devkapilbansal** [openwisp/openwrt-openwisp-monitoring#32]
```
root@E4-C3-2A-90-84-97:/usr/sbin# ./netjson_monitoring '*'
lua: ./netjson_monitoring:226: bad argument #2 to 'tonumber' (integer expected, got string)
stack traceback:
	[C]: in function 'tonumber'
	./netjson_monitoring:226: in function 'get_cpus'
	./netjson_monitoring:260: in main chunk
	[C]: ?
```
Still not sure why this error is occuring, will try to test more until I got some satisfactory results

**Comment by nemesisdesign** [comment]
I think there's some bug in lua or OpenWRT which causes this.
We may devise a retry function which retries the functions several times on errors. I tried a similar approach in the past and it worked. Not the cleanest solution but it works, which is what counts in the end.

**Comment by devkapilbansal** [comment]
I discussed this in Lua Community on their public channel some time back and they suggests me to enclose the function in quotes :thinking: 

However, I am not sure if it will work or not. :confused: 
Rest I already added a retry on the whole script because popen was failing too sometimes.
