### ISSUE TITLE
[bug] Data not sent successfully. Exit code is 127

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwrt-openwisp-monitoring#41]
While testing the daeamon I get the following:

```
Mon Jul  5 00:23:06 2021 daemon.info monitoring: Collecting NetJSoN Monitoring data
Mon Jul  5 00:23:06 2021 daemon.err monitoring: Data not sent successfully. Exit code is 127
``` 

First of all, can you please change any occurrence of output or docs mentioning "NetJSON" which is not spelled this way and end ensure follows this spelling?

Then, `Data not sent successfully. Exit code is 127` is not super helpful in finding out what's wrong.

What steps can we take in order to improve the life of users which will be using this package?
Can we include the code line and command which are failing?

**Comment by nemesisdesign** [comment]
Maybe we can add a command to trigger the same behavior of the deamon but one time, without the recurring sleep, just for testing purposes and with verbose output in CURL, which could be printed out, that would help

What do you think? @devkapilbansal @nickberry17 @feckert

**Comment by devkapilbansal** [comment]
I added a `verbose_mode` in the config file that if true can help better debug the code.
