### ISSUE TITLE
[bug] Bridge members shown even if they do not exist

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwrt-openwisp-monitoring#43]
In OpenWRT it's possible to define bridge members that do not exist, they'll be added only if they exist and be ignored otherwise.
This is pretty handy in OpenWISP because it's possible to define different bridge members which get added only if the right template is used.

@devkapilbansal can you change the code so that only existing bridge members are collected in the NetJSON monitoring output?

EG:

```json
{
    "name": "br-wifi",
    "bridge_members": [
        "wlan0",
        "wlan1",
        "tap_tcp",
        "tap_tcp_nocryp",
        "tap_udp",
        "tap_udp_nocryp"
    ]
}
```

In the case above, these members do not exist and therefore should not be added:

- "tap_tcp_nocryp",
- "tap_udp",
- "tap_udp_nocryp"

**Comment by devkapilbansal** [comment]
Hi,
If I am not wrong, I will get these information from `ip neighbors` if a bridge member exist or not :thinking:

**Comment by nemesisdesign** [comment]
@devkapilbansal `ip neighbors` won't help.

I double checked just now on a device.

The command `ubus call network.device status` (which we already use) shows all the defined members of a bridge, regardless if they're up or not. However, the same command returns a list of all the active interfaces, so by checking whether this dictionary structure contains a key with the specified interface name we can know which interfaces are active and should therefore be shown and which ones are not and should therefore not be shown.

Here's an example (some data is omitted):

```json
{
  "br-piemwifi": {                       
    "external": false,               
    "present": true,               
    "type": "bridge",              
    "up": true,                   
    "carrier": true,              
    "bridge-members": [           
      "gw1_piem_tcp",          
      "gw1_piem_udp",          
      "piem_wlan1"             
    ]
  }
}
```

As you can see there are 3 members defined, but in the same structure only `gw1_piem_udp` and `piem_wlan1` are present and flagged as `"present": true` and `"up": true`. So by checking for these 3 conditions (key being present and these 2 attributes) we should be able to solve this issue.

Is it clear @devkapilbansal?
