### ISSUE TITLE
[enhancement] Switch indentation from spaces to tabs

### ISSUE THREAD

**Issue by feckert** [openwisp/openwrt-openwisp-monitoring#58]
I know this is annoying, but in an embedded system every byte counts.
Because every byte must also be interpreted.
Therefore, tabs should always be used by shell scripts.
https://github.com/openwisp/openwrt-openwisp-monitoring/blob/gsoc21/openwrt-openwisp-monitoring/files/monitoring.agent
https://github.com/openwisp/openwrt-openwisp-monitoring/blob/gsoc21/openwrt-openwisp-monitoring/files/monitoring.init
This is also the way it is done throughout OpenWrt.

**Comment by nemesisdesign** [comment]
@feckert good point, we shall check openwisp-config too! @devkapilbansal can you do this as part of the linting changes?

**Comment by feckert** [comment]
Yes this is also true for openwisp config

**Comment by devkapilbansal** [comment]
> @feckert good point, we shall check openwisp-config too! @devkapilbansal can you do this as part of the linting changes?

Will make this changes in #53.

**Comment by feckert** [comment]
@devkapilbansal Since this is a change that affects every line, you have to do it in one step.
Therefore, all the development you have made in this lines should be merge into your development branch [gsoc21](https://github.com/openwisp/openwrt-openwisp-monitoring/tree/gsoc21), otherwise you will have to touch all  development branches` issue/*` again if they made changes to this lines as well.

**Comment by devkapilbansal** [comment]
> @devkapilbansal Since this is a change that affects every line, you have to do it in one step.

Yes, I included it now because all major PRs are merged now

**Comment by devkapilbansal** [comment]
Closed in #53
