### ISSUE TITLE
[enhancement] Do not make openwisp lua script executable

### ISSUE THREAD

**Issue by feckert** [openwisp/openwrt-openwisp-monitoring#60]
As I see it, the scripts do not have to be executable that are under `/usr/lib/lua/openwisp` on the system.
Please replace INSTALL_BIN with INSTALL_DATA in the openwrt makefile install routine.

I also noticed that the openwsip-agent also has lua scripts under /usr/lib/lua/openwisp.
Does it make sense to use a separate directory?

**Comment by nemesisdesign** [comment]
> As I see it, the scripts do not have to be executable that are under `/usr/lib/lua/openwisp` on the system.
> Please replace INSTALL_BIN with INSTALL_DATA in the openwrt makefile install routine.

Are we talking about the lua utilities that are included? Definitely no need for these to be executable.

> I also noticed that the openwsip-agent also has lua scripts under /usr/lib/lua/openwisp.
> Does it make sense to use a separate directory?

Not sure, I am ok with the way it is now but if you recommend having these in their own dir we can do so.

**Comment by devkapilbansal** [comment]
> Does it make sense to use a separate directory?

That means, I should move files from `usr/lib/lua/openwisp/monitoring` to `/usr/lib/lua/openwisp` ??

**Comment by feckert** [comment]
> > As I see it, the scripts do not have to be executable that are under `/usr/lib/lua/openwisp` on the system.
> > Please replace INSTALL_BIN with INSTALL_DATA in the openwrt makefile install routine.
> 
> Are we talking about the lua utilities that are included? Definitely no need for these to be executable.

Then we should change that. If this is not necessary.

> > I also noticed that the openwsip-agent also has lua scripts under /usr/lib/lua/openwisp.
> > Does it make sense to use a separate directory?
> 
> Not sure, I am ok with the way it is now but if you recommend having these in their own dir we can do so.

They are two separate packages openwisp-config and openwisp-monitoring, which have nothing to do with each other.
Therefore they should be in a separate directory, if they are more then one file.

**Comment by devkapilbansal** [comment]
Ohh, ohkay :+1:
