### ISSUE TITLE
[optimize] Use gzip to compress data

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwrt-openwisp-monitoring#64]
We can reduce the use of memory of more than 70% thanks to gzip.

We should just do the following:

- a basic gzip is provided by busybox, this should be enough, I am not sure whether we should specify this in the dependencies or not, we should double check this
- gzip files after saving them, eg: `gzip $path`, this command also removes the original file
- decompress files before sending the data, eg: `gzip -d $path`

**Comment by devkapilbansal** [comment]
> * a basic gzip is provided by busybox, this should be enough, I am not sure whether we should specify this in the dependencies or not, we should double check this

It would be better to specify this in dependencies.
