### ISSUE TITLE
Write lua tests

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwrt-openwisp-monitoring#7]
We need to write tests for the lua functions.

I hope we can use mocking to simulate the calls to the network programs we use to get the data (ubus, arp, etc).

**Comment by devkapilbansal** [comment]
I would like to work on this

**Comment by devkapilbansal** [comment]
I need some more time, understand the scripts. Till then, if anyone is interested they can work on this issue

**Comment by nemesisdesign** [comment]
Closed by #26.

**Comment by devkapilbansal** [comment]
Issue already solved in https://github.com/openwisp/openwrt-openwisp-monitoring/commit/91f319ab9fcb5dfef087a23ebf89a235881cff0c
