### ISSUE TITLE
[Openwrt] cannot find dependency openwisp-config for openwisp-monitoring

### ISSUE THREAD

**Issue by BlueWaterCrystal** [openwisp/openwrt-openwisp-monitoring#82]
Hi,

openwisp-config has been working fine on OpenWrt-21.02.

Config:
```
netjson-monitoring=y
openwisp-config-openssl=y
openwisp-monitoring=y
```

Error:
```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency openwisp-config for openwisp-monitoring
 * pkg_hash_fetch_best_installation_candidate: Packages for openwisp-monitoring found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package openwisp-monitoring.
 make[2]: *** [package/Makefile:69: package/install] Error 255
```

**Comment by nemesisdesign** [comment]
Try using the following:

- http://downloads.openwisp.io/?prefix=openwisp-config/latest/
- http://downloads.openwisp.io/?prefix=openwisp-monitoring/latest/

It should work. We need to update the README here.

**Comment by BlueWaterCrystal** [comment]
@nemesisdesign Thank you, how do I add it to the build as it's precompiled?

**Comment by nemesisdesign** [comment]
> @nemesisdesign Thank you, how do I add it to the build as it's precompiled?

Isn't this working for you?
https://github.com/openwisp/openwrt-openwisp-monitoring#compiling-openwrt-openwisp-monitoring

Make sure you're also following the [latest openwisp-config compile instructions](https://github.com/openwisp/openwisp-config#compiling-a-custom-openwrt-image).

You need both packages.
